version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo "Installing Sonar Scanner..."
      - curl -o sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-4.7.0.2747-linux/bin
      - echo "Sonar Scanner Installed."

  build:
    commands:
      - echo "Running SonarQube Analysis..."
      - export REPO_NAME=$(basename `git rev-parse --show-toplevel`)
      - export BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
      - sonar-scanner \
          -Dsonar.projectKey=$REPO_NAME \
          -Dsonar.branch.name=$BRANCH_NAME \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://3.84.123.130:9000 \
          -Dsonar.login=<YOUR_SONARQUBE_TOKEN>

artifacts:
  files:
    - "**/*"
